### ISSUE TITLE
Dependency on syracuse-tools

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/mathtexdotnet#2]
This project have reference dependency on [syracuse-tools](https://code.launchpad.net/syracuse-tools/) assemblies. That means I ideally need to import that project from bzr, too, and maybe upload it to NuGet or include as a git submodule here.

Maybe merge syracuse-tools here, because I currently see no use of it as a separate project.

**Comment by ForNeVeR** [comment]
Please note that, while being itself licensed by GPL, syracuse-tools repository is a subject to #1, too. So, we can change the license to MIT at the moment we import the sources.

**Comment by alexreg** [comment]
Yeah, it was a separate project, because formerly various projects within the overarching Syracuse project were using it as a common library. But that's no longer necessary I think. Maybe best to keep as a separate VSProj, but no more.
